### PR TITLE
GC-447 - Add api to ModelMatrix allowing to create definition

### PR DESCRIPTION
**Pull request by jpocalan-collective**

### CODE REVIEW

**Comment by jpocalan-collective** [comment]
@ezhulenev This is an initial commit. Wanted to have your first impression on few of the code changes I did whenever you have time. I still need to add unique constraint to checksum column and handle it. Moreover I want to "unify" whatever we are doing in AddDefinition with the createModelMatrixDefinition.

**Comment by jpocalan-collective** [comment]
latest change is simply about making checksum column unique.  Still need to work on the other points but I'll first make the dorado-modeling changes do make sure I am on the right track here.

**Comment by jpocalan-collective** [comment]
@ezhulenev for the `AddDefinition` and `ModelMatrix.createModelMatrixDefinition` code similarity I was thinking in creating a trait `DefinitionCreator` (something along this lines) with method `createDefinitionFrom(configFile: File)` which will do sort of whatever `AddDefinition` is doing in the `run()`. This means I am removing `parser` as attribute of `AddDefinition` as it will be instantiate inside the `createDefinitionFrom` method. let me know your thoughts.

**Comment by ezhulenev** [comment]
:+1: go for it

**Comment by jpocalan-collective** [comment]
@ezhulenev  ready to merge and publish to bintray if no objections

**Comment by ezhulenev** [comment]
:+1:

**Pull request merged**
